#+title: Ematrix (personal emacs configuration)
#+author: donney
#+property: header-args:emacs-lisp :tangle yes :comments link
#+property: header-args:elisp :exports code
#+property: header-args:shell :tangle "setup.sh"
#+startup: overview

* Introduction
Customising an editor can be very rewarding ... until you have to leave it.
For years I have been looking for ways to avoid this pain.
Then I discovered [[https://github.com/cknadler/vim-anywhere][vim-anywhere]], and found that it had an Emacs companion,
[[https://github.com/zachcurry/emacs-anywhere][emacs-anywhere]]. To me, this looked most attractive.

Separately, online I have seen the following statement enough times I think it's a catchphrase
#+begin_quote
Redditor 1: I just discovered this thing, isn't it cool. \\
Redditor 2: Oh, there's an Emacs mode for that.
#+end_quote

This was enough for me to install Emacs, but I soon learned there are [[https://github.com/remacs/remacs#why-emacs][far more
compelling reasons]] to keep using it.

I tried out the =spacemacs= distribution a bit, but it wasn't quite to my liking.
Then I heard about =doom emacs= and thought I may as well give that a try.
TLDR; it's great.

Now I've discovered the wonders of literate programming, and am becoming more
settled by the day. This is both my config, and a cautionary tale (just replace
"Linux" with "Emacs" in the comic below).

[[xkcd:456]]

** Why Emacs?
Emacs is [[https://www.eigenbahn.com/2020/01/12/emacs-is-no-editor][not a text editor]], this is a common misnomer. It is far more apt to
describe Emacs as /a Lisp machine providing a generic user-centric text
manipulation environment/. That's quite a mouthful.
In simpler terms one can think of Emacs as a platform for text-related
applications. It's a vague and generic definition because Emacs itself is
generic.

Good with text. How far does that go? A lot further than one initially thinks:
+ [[https://orgmode.org/][Task planning]]
+ [[https://www.gnu.org/software/emacs/manual/html_node/emacs/Dired.html][File management]]
+ [[https://github.com/akermu/emacs-libvterm][Terminal emulation]]
+ [[https://www.djcbsoftware.nl/code/mu/mu4e.html][Email client]]
+ [[https://www.gnu.org/software/tramp/][Remote server tool]]
+ [[https://magit.vc/][Git frontend]]
+ Web [[https://github.com/pashky/restclient.el][client]]/[[https://github.com/skeeto/emacs-web-server][server]]
+ and more...

Ideally, one may use Emacs as /the/ interface to perform =input → transform →
output= cycles, i.e. form a bridge between the human mind and information
manipulation.

* LOGO
#+name: logo
#+begin_src emacs-lisp :tangle no
;;;
;;; ___________               __         .__
;;; \_   _____/ _____ _____ _/  |________|__|__  ___
;;;  |    __)_ /     \\__  \\   __\_  __ \  \  \/  /
;;;  |        \  Y Y  \/ __ \|  |  |  | \/  |>    <
;;; /_______  /__|_|  (____  /__|  |__|  |__/__/\_ \
;;;         \/      \/     \/                     \/
;;;
;;; MINIMALIST & LIGHTWEIGHT EMACS CONFIGURATION FRAMEWORK
;;; donneyluck.github.io/ematrix
;;;
;;; Author: donneyluck@gmail.com
;;; Copyright (C) 2022-2024  Machine Studio
;;;
#+end_src

* init.el
#+name: init.el
#+attr_html: :collapsed t
** header
#+begin_src emacs-lisp :tangle "init.el" :noweb no-export
;; init.el --- Ematrix core initialization file -*- lexical-binding: t; -*-
<<logo>>
;;; Commentary:
#+end_src
** load and hooks order
#+begin_src emacs-lisp :tangle "init.el"
;; # Ematrix - a minimalist & lightweight Emacs configuration framework
;;
;; Load and hooks order:
;; - `~/.emacs.d/early-init.el`
;; - `$EMATRIXDIR/early-config.el` (unless disabled in `$EMATRIX_IGNORE_USER_CONFIG`)
;; - `$EMATRIXDIR/local/early-config.el` (unless disabled)
;; - `~/.emacs.d/init.el`
;;   * `before-init-hook'
;;   * `~/.emacs.d/core/me-vars.el`
;;   * `~/.emacs.d/core/backports/*.el` (when Emacs < 29)
;;   * `~/.emacs.d/core/me-loaddefs.el`
;;   * `$EMATRIXDIR/init-tweaks.el` (unless disabled)
;;   * `$EMATRIXDIR/local/init-tweaks.el` (unless disabled)
;;   * `$EMATRIXDIR/modules.el` (unless disabled)
;;   * `$EMATRIXDIR/local/modules.el` (unless disabled)
;;   * `~/.emacs.d/core/<module>.el`
;;   * `~/.emacs.d/modules/<module>.el` (for module in `ematrix-modules')
;;   * `ematrix-after-loading-modules-hook'
;;   * `$EMATRIXDIR/custom-vars.el`
;;   * `$EMATRIXDIR/config.el` (unless disabled)
;;   * `$EMATRIXDIR/local/config.el` (unless disabled)
;;   * `after-init-hook'
;;   * `emacs-startup-hook'
;;   * `ematrix-after-startup-hook'
;;     + `ematrix-lazy-hook' (delayed)

;; Special hooks defined with `+make-first-file-hook!'
;; - `ematrix-first-file-hook'
;; - `ematrix-first-elisp-file-hook'
;; - `ematrix-first-python-file-hook'
;; - `ematrix-first-org-file-hook'
;; - `ematrix-first-c/c++-file-hook'

;;; Code:
#+end_src
